### ISSUE TITLE
[BUG] Illegal memory access error with nvcc "-G" on H100

### ISSUE THREAD

**Issue by ipiszy** [NVIDIA/cutlass#1044]
**Describe the bug**
"illegal memory access" error from a cutlass lib compiled with nvcc option "-G" on H100. The lib runs successfully without "-G" option. 

**Steps/Code to reproduce bug**
1. test.cu: https://gist.github.com/ipiszy/9a6ade3e651cda31d730fddfb6e5626f
2. compilation commandline: https://gist.github.com/ipiszy/555f91565240cfc5d6ba72de0eb177c5
Compilation log:
```
nvcc warning : '--device-debug (-G)' overrides '--generate-line-info (-lineinfo)'
ptxas info    : (C7505) Potential Performance Loss: 'setmaxnreg' ignored to allow debugging.
ptxas info    : (C7509) Potential Performance Loss: wgmma.mma_async instructions are serialized due to the presence of Extern calls in the function '_ZN7cutlass13device_kernelI88cutlass3x_sm90_tensorop_h64x128x16gemm_f16_f16_f16_f16_f16_128x128x64_2x1x1_0_tnt_align8EEvNT_6ParamsE'
ptxas info    : (C7511) Potential Performance Loss: wgmma.mma_async instructions are serialized due to insufficient register resources for the wgmma pipeline in the function '_ZN4cute27SM90_64x128x16_F16F16F16_SSILNS_4GMMA5MajorE0ELS2_0ELNS1_7ScaleInE1ELS3_1EE3fmaERKmS6_RjS7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_S7_NS1_8ScaleOutE'
/home/yingz/pytorch/torch/../third_party/cutlass/include/cutlass/device_kernel.h: In function ‘void cutlass::device_kernel(typename Operator::Params) [with Operator = cutlass3x_sm90_tensorop_h64x128x16gemm_f16_f16_f16_f16_f16_128x128x64_2x1x1_0_tnt_align8]’:
/home/yingz/pytorch/torch/../third_party/cutlass/include/cutlass/device_kernel.h:107:1: note: The ABI for passing parameters with 64-byte alignment has changed in GCC 4.6
 void device_kernel(CUTLASS_GRID_CONSTANT typename Operator::Params const params)
 ^~~~~~~~~~~~~
```
3. test.py: https://gist.github.com/ipiszy/08afa5eb3e2677465871ad49e26649ae
4. Run test.py: python3.8 test.py test.so
Error log:
```
X: 0x7fed99e0fa00
W: 0x7fed99e17800
Y: 0x7fed80dd0a00
workspace size: (nil)
workspace: (nil)
stream: (nil)
/home/yingz/pytorch/torch/../third_party/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:269  GemmUniversal::initialize() - workspace 0x7fed99e0fa00, stream: null
/home/yingz/pytorch/torch/../third_party/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:272    workspace_bytes: 0
/home/yingz/pytorch/torch/../third_party/cutlass/include/cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_cooperative.hpp:160  to_underlying_arguments():
/home/yingz/pytorch/torch/../third_party/cutlass/include/cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_cooperative.hpp:175    WARNING: Arguments do not include a valid SM count.
  For optimal performance, populate the arguments KernelHardwareInfo struct with the SM count.
/home/yingz/pytorch/torch/../third_party/cutlass/include/cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_cooperative.hpp:179  to_underlying_arguments(): Setting persistent grid SM count to 132
/home/yingz/pytorch/torch/../third_party/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:297    Setting smem size to 229760
/home/yingz/pytorch/torch/../third_party/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:329  GemmUniversal::run()
/home/yingz/pytorch/torch/../third_party/cutlass/include/cutlass/gemm/kernel/sm90_tile_scheduler.hpp:142  get_grid_shape(): Persistent schedule grid plan using SM count = 132
/home/yingz/pytorch/torch/../third_party/cutlass/include/cutlass/cluster_launch.hpp:150  ClusterLauncher: Launching GPC_CLUSTER_GRID GridDims = (64, 1, 1), And ClusterDims = (2, 1, 1)

[ ERROR: CUDA Runtime ] /home/yingz/pytorch/torch/../third_party/cutlass/include/cutlass/cluster_launch.hpp:153: an illegal memory access was encountered
/home/yingz/pytorch/torch/../third_party/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:356    Kernel launch failed. Reason: an illegal memory access was encountered
[/tmp/torchinductor_yingz/ux/cuxglfnc3v4l5j7fmsvibev5bsb3zuzh3mkamnqwxhyekuzbux3b.cu] Got cutlass error: Error Internal at: 189
Traceback (most recent call last):
  File "/home/yingz/test.py", line 27, in <module>
    torch.cuda.synchronize()
  File "/home/yingz/pytorch/torch/cuda/__init__.py", line 783, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

5. If remove the "-G" option in 2, it runs successfully.

**Expected behavior**
test.py runs successfully.

**Environment details (please complete the following information):**
 - Environment location: Bare-metal
 - nvcc version:
 ```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
```
- CUDA env from `nvidia-smi`
```
NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0
```
- gcc version
```
gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-20)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Additional context**

**Comment by ipiszy** [comment]
cc @thakkarV @hwu36

**Comment by hwu36** [comment]
have you tried 12.2?

**Comment by ipiszy** [comment]
No, this is from 12.1 cuda toolkit installation.

**Comment by mnicely** [comment]
Hi @ipiszy any luck with this issue?

**Comment by hwu36** [comment]
We can confirm now that it is an nvcc bug.  The fix is on the way.

**Comment by mnicely** [comment]
@ipiszy this should be fixed in 12.3. I'm going to close the bug for now. Please reopen if you're still having issues.

**Comment by fei-xx** [comment]
@mnicely and @hwu36, this issue happened again in the main branch:

```
CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=1 python test.py cutlass/scripts/test.so 
X: 0x7f6e41e0fa00
W: 0x7f6e41e17800
Y: 0x7f6e283d0a00
workspace size: (nil)
workspace: (nil)
stream: (nil)
cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:283  GemmUniversal::initialize() - workspace 0, stream: null
cutlass/include/cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_cooperative.hpp:168  to_underlying_arguments():
cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_cooperative.hpp:181    WARNING: Arguments do not include a valid SM count.
  For optimal performance, populate the arguments KernelHardwareInfo struct with the SM count.
cutlass/include/cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_cooperative.hpp:186  to_underlying_arguments(): Setting persistent grid SM count to 132
cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:309    Setting smem size to 229888
cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:346  GemmUniversal::run()
cutlass/include/cutlass/cluster_launch.hpp:148  ClusterLauncher: Launching GPC_CLUSTER_GRID GridDims = (2, 32, 1), And ClusterDims = (2, 1, 1)

[ ERROR: CUDA Runtime ] /home/fhu/git/cutlass/include/cutlass/cluster_launch.hpp:154: misaligned address
/home/fhu/git/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:414    Kernel launch failed. Reason: misaligned address
[test.cu] Got cutlass error: Error Internal at: 189
Traceback (most recent call last):
  File "cutlass/scripts/test.py", line 27, in <module>
    torch.cuda.synchronize()
  File "/usr/local/lib/python3.11/site-packages/torch/cuda/__init__.py", line 696, in synchronize
    return torch._C._cuda_synchronize()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: misaligned address
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

- gcc version
```
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
- nvcc version
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
```
- nvidia-smi
```
NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2  
```

**Comment by hwu36** [comment]
As @mnicely said earlier, you need to use nvcc 12.3+

**Comment by fei-xx** [comment]
Thanks @hwu36 for the quick response! It works now.
