### ISSUE TITLE
[QST] cudaFuncSetAttribute() returned error: invalid resource handle

### ISSUE THREAD

**Issue by rehsuuuuuuuu** [NVIDIA/cutlass#2478]
**What is your question?**
Hi, I am currently encounter the following problem

I am currently running on RTX 5080 and I have tested runing example 79a, it went smooth.

At the mean time I am trying to add a custom torch API to it. So basically I kept most of the code structures of example 79a, but only insert my own input/output/scale factor pointers, and using pybind to link the kernel to torch.

Then I encountered the problem that the code complies but the kernel lauch failed

the log is here

/home/cutlass_test/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:244    workspace_bytes: 0
/home/cutlass_test/cutlass/tools/util/include/cutlass/util/device_memory.h:75  cutlass::device_memory::allocate: Successful cudaMalloc: bytes=0
/home/cutlass_test/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:312  GemmUniversal::initialize() - workspace 0, stream: null
/home/cutlass_test/cutlass/include/cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_cooperative.hpp:201  to_underlying_arguments():
/home/cutlass_test/cutlass/include/cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_cooperative.hpp:214    WARNING: Arguments do not include a valid SM count.
  For optimal performance, populate the arguments KernelHardwareInfo struct with the SM count.
/home/cutlass_test/cutlass/include/cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_cooperative.hpp:218  to_underlying_arguments(): Setting persistent grid SM count to 84
/home/cutlass_test/cutlass/include/cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_cooperative.hpp:224    WARNING: Arguments do not include a valid max cluster count.
  For optimal performance, populate the arguments KernelHardwareInfo struct with the max_active_clusters.
/home/cutlass_test/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:336    Setting smem size to 88064
/home/cutlass_test/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:343    cudaFuncSetAttribute() returned error: invalid resource handle
/home/cutlass_test/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:372  GemmUniversal::run()
/home/cutlass_test/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:383  GemmUniversal::run: Use extended launch API
/home/cutlass_test/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:479  GemmUniversal::run: Launching static 1x1x1 kernel
/home/cutlass_test/cutlass/include/cutlass/kernel_launch.h:84  cutlass::kernel_launch
/home/cutlass_test/cutlass/include/cutlass/kernel_launch.h:89  cutlass::kernel_launch: No PDL
/home/cutlass_test/cutlass/include/cutlass/kernel_launch.h:135    Kernel launch failed. Reason: invalid device function
/home/cutlass_test/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:483  GemmUniversal::run: cutlass::kernel_launch reports failure
/home/cutlass_test/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:558    Kernel launch failed. Reason: no error

the kernel structure I mostly adopted from 
https://github.com/ColfaxResearch/cfx-article-src/blob/master/cutlass_gemm/cutlass_gemm/cutlass_gemm.hpp
And I also encountered the same problem when lauching their kernel on Hopper(adopted from example 48). Only the default kernel which uses the 2.x syntax compiles and runs with the correct output

**Comment by thakkarV** [comment]
Need more details to help you debug like your CTK version, host toolchain, driver etc. but without that, here is:

https://stackoverflow.com/questions/6021449/cuda-invalid-resource-handle

**Comment by rehsuuuuuuuu** [comment]
Thanks for the reply. I am using 

Cuda compilation tools, release 12.8, V12.8.93
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
driver version: 570.144 

When I run on excamples through cutlass/build, everything is normal and i got the correct output, with logs like
```
/home/cutlass_test/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:244    workspace_bytes: 0
/home/cutlass_test/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:312  GemmUniversal::initialize() - workspace 0, stream: null
/home/cutlass_test/cutlass/include/cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_cooperative.hpp:201  to_underlying_arguments():
/home/cutlass_test/cutlass/include/cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_cooperative.hpp:214    WARNING: Arguments do not include a valid SM count.
  For optimal performance, populate the arguments KernelHardwareInfo struct with the SM count.
/home/cutlass_test/cutlass/include/cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_cooperative.hpp:218  to_underlying_arguments(): Setting persistent grid SM count to 84
/home/cutlass_test/cutlass/include/cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_cooperative.hpp:224    WARNING: Arguments do not include a valid max cluster count.
  For optimal performance, populate the arguments KernelHardwareInfo struct with the max_active_clusters.
/home/cutlass_test/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:336    Setting smem size to 88064
/home/cutlass_test/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:372  GemmUniversal::run()
  Disposition: Passed
```

but on my custom version, what I essentially change is the input pointers (which are valid since using old cutlass 2.x kernel it outputs the correct answer)

When I run on the quoted repo above on Hopper kernel (namely example 48) I also got, instead of invalid resource handle, another another on the same line:
/home/cutlass_test/cutlass/include/cutlass/gemm/device/gemm_universal_adapter.h:343    cudaFuncSetAttribute() returned error: invalid argument

The step where the bug happens is when executing 
`gemm_op.initialize(arguments, workspace.get());
`
The kernel I am using:

```
#include <iostream>

#include "cutlass/cutlass.h"

#include "cute/tensor.hpp"
#include "cutlass/tensor_ref.h"
#include "cutlass/epilogue/thread/linear_combination.h"
#include "cutlass/gemm/dispatch_policy.hpp"
#include "cutlass/gemm/collective/collective_builder.hpp"
#include "cutlass/epilogue/collective/collective_builder.hpp"
#include "cutlass/detail/sm100_blockscaled_layout.hpp"
#include "cutlass/gemm/device/gemm_universal_adapter.h"
#include "cutlass/gemm/kernel/gemm_universal.hpp"
#include "cutlass/gemm/kernel/tile_scheduler_params.h"

#include "cutlass/util/command_line.h"
#include "cutlass/util/distribution.h"
#include "cutlass/util/host_tensor.h"
#include "cutlass/util/packed_stride.hpp"
#include "cutlass/util/tensor_view_io.h"
#include "cutlass/util/reference/device/gemm.h"
#include "cutlass/util/reference/device/tensor_compare.h"
#include "cutlass/util/reference/host/tensor_fill.h"
#include "cutlass/util/reference/host/gett.hpp"
#include "cutlass/util/reference/host/tensor_norm.h"
#include "cutlass/util/reference/host/tensor_compare.h"

using namespace cute;

template<typename DataType, typename ScaleFactorType, typename OutputType> void gemm_cutlass_wrapper(int M, int N, int K, DataType const* ptrA, DataType const* ptrB, ScaleFactorType const* ptrA_scl, ScaleFactorType const* ptrB_scl, OutputType* ptrD){
  /////////////////////////////////////////////////////////////////////////////////////////////////
  /// GEMM kernel configurations
  /////////////////////////////////////////////////////////////////////////////////////////////////

  // A matrix configuration
  using         ElementA    = cutlass::nv_float4_t<cutlass::float_e2m1_t>;    // Element type for A matrix operand
  using         LayoutATag  = cutlass::layout::RowMajor;                      // Layout type for A matrix operand
  constexpr int AlignmentA  = 32;                                             // Memory access granularity/alignment of A matrix in units of elements (up to 16 bytes)

  // B matrix configuration
  using         ElementB    = cutlass::nv_float4_t<cutlass::float_e2m1_t>;    // Element type for B matrix operand
  using         LayoutBTag  = cutlass::layout::ColumnMajor;                   // Layout type for B matrix operand
  constexpr int AlignmentB  = 32;                                             // Memory access granularity/alignment of B matrix in units of elements (up to 16 bytes)

  // C/D matrix configuration
  using         ElementD    = cutlass::bfloat16_t;                            // Element type for D matrix operand
  using         ElementC    = cutlass::bfloat16_t;                            // Element type for C matrix operand
  using         LayoutCTag  = cutlass::layout::RowMajor;                      // Layout type for C matrix operand
  using         LayoutDTag  = cutlass::layout::RowMajor;                      // Layout type for D matrix operand
  constexpr int AlignmentD  = 128 / cutlass::sizeof_bits<ElementC>::value;    // Memory access granularity/alignment of C matrix in units of elements (up to 16 bytes)
  constexpr int AlignmentC  = 128 / cutlass::sizeof_bits<ElementD>::value;    // Memory access granularity/alignment of C matrix in units of elements (up to 16 bytes)
  // Kernel functional config
  using ElementAccumulator  = float;                                          // Element type for internal accumulation
  using ArchTag             = cutlass::arch::Sm120;                           // Tag indicating the minimum SM that supports the intended feature
  using OperatorClass       = cutlass::arch::OpClassBlockScaledTensorOp;      // Operator class tag

  // Kernel Perf config
  using ThreadBlockShape    = Shape<_128,_128,_128>;                          // Threadblock's tile size
  using ClusterShape        = Shape<_1,_1,_1>;                                // Shape of the threadblocks in a cluster

  using CollectiveEpilogue = typename cutlass::epilogue::collective::CollectiveBuilder<
      ArchTag, OperatorClass,
      ThreadBlockShape, ClusterShape,
      cutlass::epilogue::collective::EpilogueTileAuto,
      ElementAccumulator, ElementAccumulator,
      ElementC, LayoutCTag, AlignmentC,
      ElementD, LayoutDTag, AlignmentD,
      cutlass::epilogue::collective::EpilogueScheduleAuto                      // Epilogue schedule policy
    >::CollectiveOp;

  using CollectiveMainloop = typename cutlass::gemm::collective::CollectiveBuilder<
      ArchTag, OperatorClass,
      ElementA, LayoutATag, AlignmentA,
      ElementB, LayoutBTag, AlignmentB,
      ElementAccumulator,
      ThreadBlockShape, ClusterShape,
      cutlass::gemm::collective::StageCountAutoCarveout<static_cast<int>(sizeof(typename CollectiveEpilogue::SharedStorage))>,
      cutlass::gemm::collective::KernelScheduleAuto                             // Kernel schedule policy. Auto defaults to cooperative kernel schedule
    >::CollectiveOp;

  using GemmKernel = cutlass::gemm::kernel::GemmUniversal<
      Shape<int,int,int,int>,                                                   // Indicates ProblemShape
      CollectiveMainloop,
      CollectiveEpilogue,
      void>;

  using Gemm = cutlass::gemm::device::GemmUniversalAdapter<GemmKernel>;

  // Reference device GEMM implementation type
  using StrideA   = typename Gemm::GemmKernel::StrideA;
  using LayoutA   = decltype(cute::make_layout(cute::make_shape(0,0,0), StrideA{}));
  using LayoutSFA = typename Gemm::GemmKernel::CollectiveMainloop::LayoutSFA;      // Scale Factor tensors have an interleaved layout. Bring Layout instead of stride.
  using StrideB   = typename Gemm::GemmKernel::StrideB;
  using LayoutB   = decltype(cute::make_layout(cute::make_shape(0,0,0), StrideB{}));
  using LayoutSFB = typename Gemm::GemmKernel::CollectiveMainloop::LayoutSFB;      // Scale Factor tensors have an interleaved layout. Bring Layout instead of stride.
  using StrideC   = typename Gemm::GemmKernel::StrideC;
  using LayoutC   = decltype(cute::make_layout(cute::make_shape(0,0,0), StrideC{}));
  using StrideD   = typename Gemm::GemmKernel::StrideD;
  using LayoutD   = decltype(cute::make_layout(cute::make_shape(0,0,0), StrideD{}));

  //
  // Data members
  //

  float alpha = 1.0f;
  float beta = 0.0f;

  /// Initialization
  StrideA stride_A;
  LayoutA layout_A;
  LayoutSFA layout_SFA;
  StrideB stride_B;
  LayoutB layout_B;
  LayoutSFB layout_SFB;
  StrideC stride_C;
  LayoutC layout_C;
  StrideD stride_D;
  LayoutD layout_D;

  using Sm1xxBlkScaledConfig =  typename Gemm::GemmKernel::CollectiveMainloop::Sm1xxBlkScaledConfig;

  stride_A = cutlass::make_cute_packed_stride(StrideA{}, cute::make_shape(M, K, 1));
  stride_B = cutlass::make_cute_packed_stride(StrideB{}, cute::make_shape(N, K, 1));
  stride_C = cutlass::make_cute_packed_stride(StrideC{}, cute::make_shape(M, N, 1));
  stride_D = cutlass::make_cute_packed_stride(StrideD{}, cute::make_shape(M, N, 1));

  layout_A = cute::make_layout(cute::make_shape(M, K, 1), stride_A);
  layout_B = cute::make_layout(cute::make_shape(N, K, 1), stride_B);
  layout_C = cute::make_layout(cute::make_shape(M, N, 1), stride_C);
  layout_D = cute::make_layout(cute::make_shape(M, N, 1), stride_D);
  layout_SFA = Sm1xxBlkScaledConfig::tile_atom_to_shape_SFA(cute::make_shape(M, N, K, 1));
  layout_SFB = Sm1xxBlkScaledConfig::tile_atom_to_shape_SFB(cute::make_shape(M, N, K, 1));
  

  // Instantiate CUTLASS kernel depending on templates
  Gemm gemm_op;

  // Create a structure of gemm kernel arguments suitable for invoking an instance of Gemm
  typename Gemm::Arguments arguments {
    cutlass::gemm::GemmUniversalMode::kGemm,
    {M, N, K, 1},
    { // Mainloop arguments
      ptrA, stride_A,
      ptrB, stride_B,
      ptrA_scl, layout_SFA,
      ptrB_scl, layout_SFB
    },
    { // Epilogue arguments
      {alpha, beta},
      nullptr, stride_C,
      ptrD, stride_D
    }
  };

  // Using the arguments, query for extra workspace required for matrix multiplication computation
  size_t workspace_size = Gemm::get_workspace_size(arguments);

  // Allocate workspace memory
  cutlass::device_memory::allocation<uint8_t> workspace(workspace_size);

  // Check if the problem size is supported or not
  gemm_op.can_implement(arguments);

  // Initialize CUTLASS kernel with arguments and workspace pointer
  gemm_op.initialize(arguments, workspace.get());

  // Correctness / Warmup iteration
  gemm_op.run();

  cudaDeviceSynchronize();
}
```

**Comment by thakkarV** [comment]
I thought it was reporting invalid resource not invalid argument. did that change?

**Comment by rehsuuuuuuuu** [comment]
Sorry for not making things clear and causing any confusions.

The whole point of my project is trying to set up a fp4 cutlass gemm kernel with Torch API. I used similar structure to the one repo i quoted eariler, whose kernel structure is from cutlass/example48 (for Hopper of course). When I run this on my Blackwell GPU (namely rtx5080) I got invalid arguement error (which could be incompatible hardware architecture issues but it is not what I was look at)

The kernel above I used is mostly from example79a, and it is this kernel I have the invalid resource error. The strange part is when I run cutlass build with the exact example, it passed. By looking at the logs, the problem is when 
`gemm_op.initialize(arguments, workspace.get()); ` is called in the gemm_universal_adapter class and 
`cudaError_t result = cudaFuncSetAttribute(
            device_kernel<GemmKernel>,
            cudaFuncAttributeMaxDynamicSharedMemorySize,
            smem_size);`
function is invoked. I suspect that it is because device_kernel<GemmKernel> is not of __global__ scope and causing this error, but I am still trying to confirm that. So I really appreciate if there is any additional inform or help. 

=================================================================================
update:
This error is gone when I move the template function only including the later part (Initialization after) to a non-template function in .cu file from this .hpp file.

**Comment by thakkarV** [comment]
> update: This error is gone when I move the template function only including the later part (Initialization after) to a non-template function in .cu file from this .hpp file.

Is your problem solved with this?

**Comment by rehsuuuuuuuu** [comment]
Yes. The issue is solved. Thank you very much.

**Comment by LRLVEC** [comment]
Same problem, seems to be a nvcc compiler bug.
